export const POLL_TEST_ACTION = 'POLL_TEST_ACTION';

export const GET_POLLS_BEGIN = 'GET_POLLS_BEGIN';
export const GET_POLLS_SUCCESS = 'GET_POLLS_SUCCESS';
export const GET_POLLS_FAILURE = 'GET_POLLS_FAILURE';
