export const POLL_TEST_ACTION = 'POLL_TEST_ACTION';
export const FETCH_POLLS_BEGIN = 'FETCH_POLLS_BEGIN';
export const FETCH_POLLS_SUCCESS = 'FETCH_POLLS_SUCCESS';
export const FETCH_POLLS_FAILURE = 'FETCH_POLLS_FAILURE';
export const FETCH_POLLS_DISMISS_ERROR = 'FETCH_POLLS_DISMISS_ERROR';
